### ISSUE TITLE
Sitecom WLR-4000/4004 routers default WPA generator, ( 

### ISSUE THREAD

**Issue by hkm** [hkm/routerpwn.com#66]
"I discovered a small bug in the Sitecom WLR-4000/4004 routers default WPA generator, ( http://www.routerpwn.com/Sitecom/ )

In SCRIPTS.JS change in ROW 130, 
	    magic3f = offsets[i];
in to 
	    magic3f = offsets[j];      <-  I changed to  J

Thanks for your time 

Lars The 18Th ( CINIC Systems)"

**Comment by flex-lm** [comment]
fixed
